insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('vehicles','ambulance','Ambulancia','Ambulance','AM-biu-lans',11),
  ('vehicles','boat','Bote','Boat','bout',12),
  ('vehicles','crane','Gria','Crane','krein',13),
  ('vehicles','excavator','Excavadora','Excavator','EKS-ka-vei-tor',14),
  ('vehicles','motorcycle','Motocicleta','Motorcycle','MOU-tor-sai-kel',15),
  ('vehicles','scooter','Scooter','Scooter','SKU-ter',16),
  ('vehicles','submarine','Submarino','Submarine','SAB-ma-rin',17),
  ('vehicles','van','Camioneta','Van','van',18),
  ('vehicles','hot-air-balloon','Globo aerostatico','Hot Air Balloon','jot er ba-LUN',19),
  ('vehicles','taxi','Taxi','Taxi','TAK-si',20),
  ('space','alien','Extraterrestre','Alien','EI-lien',1),
  ('space','astronaut','Astronauta','Astronaut','AS-tro-not',2),
  ('space','comet','Cometa','Comet','KO-met',3),
  ('space','moon','Luna','Moon','mun',4),
  ('space','planet','Planeta','Planet','PLA-net',5),
  ('space','rocket','Cohete','Rocket','RO-ket',6),
  ('space','saturn','Saturno','Saturn','SA-turn',7),
  ('space','star','Estrella','Star','star',8),
  ('space','sun','Sol','Sun','san',9),
  ('space','ufo','Platillo volador','UFO','iu-ef-OU',10),
  ('space','earth','La Tierra','Earth','erz',11),
  ('space','galaxy','Galaxia','Galaxy','GA-lak-si',12),
  ('space','jupiter','Jupiter','Jupiter','LLU-pi-ter',13),
  ('space','mars','Marte','Mars','mars',14),
  ('space','nebula','Nebulosa','Nebula','NE-biu-la',15),
  ('space','satellite','Satelite','Satellite','SA-te-lait',16),
  ('space','space-rover','Explorador espacial','Space Rover','spais ROU-ver',17),
  ('space','space-station','Estacion espacial','Space Station','spais STEI-shon',18),
  ('space','meteor','Meteoro','Meteor','MII-tior',19),
  ('space','telescope','Telescopio','Telescope','TE-les-koup',20),
  ('princesses-castle','baby-dragon','Dragon bebe','Baby Dragon','BEI-bi DRA-gon',1),
  ('princesses-castle','castle','Castillo','Castle','KA-sel',2),
  ('princesses-castle','crown','Corona','Crown','kraun',3),
  ('princesses-castle','fairy','Hada','Fairy','FE-ri',4),
  ('princesses-castle','king','Rey','King','king',5),
  ('princesses-castle','prince','Principe','Prince','prins',6),
  ('princesses-castle','princess','Princesa','Princess','PRIN-ses',7),
  ('princesses-castle','queen','Reina','Queen','kuiin',8),
  ('princesses-castle','unicorn','Unicornio','Unicorn','IU-ni-korn',9),
  ('princesses-castle','wizard','Mago','Wizard','UI-sard',10),
  ('princesses-castle','dragon','Dragon','Dragon','DRA-gon',11),
  ('princesses-castle','genie','Genio','Genie','LLI-ni',12),
  ('princesses-castle','knight','Caballero','Knight','nait',13),
  ('princesses-castle','magic-book','Libro magico','Magic Book','MA-llik buk',14),
  ('princesses-castle','magic-wand','Varita magica','Magic Wand','MA-llik uond',15),
  ('princesses-castle','mermaid','Sirena','Mermaid','MER-meid',16),
  ('princesses-castle','pegasus','Pegaso','Pegasus','PE-ga-sus',17),
  ('princesses-castle','throne','Trono','Throne','zroun',18),
  ('princesses-castle','treasure-chest','Cofre del tesoro','Treasure Chest','TRE-sher chest',19),
  ('princesses-castle','witch','Bruja','Witch','uich',20),
  ('food','cake','Pastel','Cake','keik',3),
  ('food','cookie','Galleta','Cookie','KU-ki',5),
  ('food','cupcake','Panquecito','Cupcake','KAP-keik',6),
  ('food','ice-cream','Helado','Ice Cream','ais kriim',7),
  ('food','pizza','Pizza','Pizza','PIT-sa',8),
  ('food','bread','Pan','Bread','bred',9),
  ('food','candy','Dulce','Candy','KAN-di',10),
  ('food','cheese','Queso','Cheese','chiis',11),
  ('food','donut','Dona','Donut','DOU-nat',12),
  ('food','french-fries','Papas fritas','French Fries','french frais',13),
  ('food','hamburger','Hamburguesa','Hamburger','JAM-ber-ger',14),
  ('food','hot-dog','Hot dog','Hot Dog','jot dog',15),
  ('food','pancake','Panqueque','Pancake','PAN-keik',16),
  ('food','popcorn','Palomitas','Popcorn','POP-korn',17),
  ('food','soup','Sopa','Soup','sup',18),
  ('food','spaghetti','Espagueti','Spaghetti','spa-GE-ti',19),
  ('food','taco','Taco','Taco','TA-kou',20),
  ('food','egg','Huevo','Egg','eg',21),
  ('food','pie','Tarta','Pie','pai',22),
  ('food','sandwich','Sandwich','Sandwich','SAND-uich',23),
  ('fruits','apple','Manzana','Apple','A-pel',1),
  ('fruits','banana','Platano','Banana','ba-NA-na',2),
  ('fruits','strawberry','Fresa','Strawberry','STRO-be-ri',9),
  ('fruits','watermelon','Sandia','Watermelon','UO-ter-me-lon',10),
  ('fruits','blueberry','Arandano','Blueberry','BLU-be-ri',11),
  ('fruits','cherry','Cereza','Cherry','CHE-ri',12),
  ('fruits','coconut','Coco','Coconut','KO-ko-nat',13),
  ('fruits','fig','Higo','Fig','fig',14),
  ('fruits','melon','Melon','Melon','ME-lon',15),
  ('fruits','peach','Durazno','Peach','piich',16),
  ('fruits','pear','Pera','Pear','per',17),
  ('fruits','plum','Ciruela','Plum','plam',18),
  ('fruits','raspberry','Frambuesa','Raspberry','RAS-be-ri',19),
  ('fruits','tangerine','Mandarina','Tangerine','tan-lle-RIN',20),
  ('fruits','grapefruit','Toronja','Grapefruit','GREIP-frut',21),
  ('fruits','grapes','Uvas','Grapes','greips',22),
  ('fruits','kiwi','Kiwi','Kiwi','KI-ui',23),
  ('fruits','lemon','Limon','Lemon','LE-mon',24),
  ('fruits','mango','Mango','Mango','MAN-gou',25),
  ('fruits','pineapple','Pina','Pineapple','PAIN-a-pel',26),
  ('vegetables','carrot','Zanahoria','Carrot','KE-rot',4),
  ('vegetables','beet','Betabel','Beet','biit',5),
  ('vegetables','corn','Elote','Corn','korn',6),
  ('vegetables','eggplant','Berenjena','Eggplant','EG-plant',7),
  ('vegetables','garlic','Ajo','Garlic','GAR-lik',8),
  ('vegetables','mushroom','Champignon','Mushroom','MASH-rum',9),
  ('vegetables','onion','Cebolla','Onion','A-nion',10),
  ('vegetables','pea','Chicharo','Pea','pii',11),
  ('vegetables','pepper','Pimiento','Pepper','PE-per',12),
  ('vegetables','broccoli','Brocoli','Broccoli','BRO-co-li',13),
  ('vegetables','cabbage','Repollo','Cabbage','KA-bill',14),
  ('vegetables','cauliflower','Coliflor','Cauliflower','KO-li-flau-er',15),
  ('vegetables','celery','Apio','Celery','SE-le-ri',16),
  ('vegetables','cucumber','Pepino','Cucumber','KIU-kam-ber',17),
  ('vegetables','lettuce','Lechuga','Lettuce','LE-tus',18),
  ('vegetables','potato','Papa','Potato','po-TEI-tou',19),
  ('vegetables','radish','Rabano','Radish','RA-dish',20),
  ('vegetables','spinach','Espinaca','Spinach','SPI-nich',21),
  ('vegetables','tomato','Tomate','Tomato','to-MEI-tou',22),
  ('sports','basketball','Basquetbol','Basketball','BAS-ket-bol',1),
  ('sports','bicycle','Bicicleta','Bicycle','BAI-si-kel',2),
  ('sports','jump-rope','Cuerda','Jump Rope','llamp roup',3),
  ('sports','kite','Papalote','Kite','kait',4),
  ('sports','medal','Medalla','Medal','ME-dal',5),
  ('sports','roller-skate','Patines','Roller Skate','ROU-ler skeit',6),
  ('sports','skateboard','Patineta','Skateboard','SKEIT-bord',7),
  ('sports','soccer-ball','Balon','Soccer Ball','SO-ker bol',8),
  ('sports','tennis','Tenis','Tennis','TE-nis',9),
  ('sports','trophy','Trofeo','Trophy','TROU-fi',10),
  ('sports','bowling','Boliche','Bowling','BOU-ling',11),
  ('sports','boxing-gloves','Guantes de box','Boxing Gloves','BOK-sing glavs',12),
  ('sports','football','Futbol americano','Football','FUT-bol',13),
  ('sports','golf','Golf','Golf','golf',14),
  ('sports','ice-skates','Patines de hielo','Ice Skates','ais skeits',15),
  ('sports','skis','Esquis','Skis','skiis',16),
  ('sports','volleyball','Voleibol','Volleyball','VO-li-bol',17),
  ('sports','baseball','Beisbol','Baseball','BEIS-bol',18),
  ('sports','baseball-bat','Bate','Baseball Bat','BEIS-bol bat',19),
  ('sports','hockey-stick','Palo de hockey','Hockey Stick','JO-ki stik',20),
  ('jobs','chef','Cocinero','Chef','shef',1),
  ('jobs','doctor','Doctor','Doctor','DOK-tor',2),
  ('jobs','farmer','Granjero','Farmer','FAR-mer',3),
  ('jobs','firefighter','Bombero','Firefighter','FAIR-fai-ter',4),
  ('jobs','nurse','Enfermera','Nurse','ners',5),
  ('jobs','painter','Pintor','Painter','PEIN-ter',6),
  ('jobs','pilot','Piloto','Pilot','PAI-lot',7),
  ('jobs','police-officer','Policia','Police Officer','po-LIS O-fi-ser',8),
  ('jobs','teacher','Maestro','Teacher','TII-cher',9),
  ('jobs','vet','Veterinario','Vet','vet',10),
  ('jobs','barber','Barbero','Barber','BAR-ber',11),
  ('jobs','carpenter','Carpintero','Carpenter','KAR-pen-ter',12),
  ('jobs','dentist','Dentista','Dentist','DEN-tist',13),
  ('jobs','fisherman','Pescador','Fisherman','FI-sher-man',14),
  ('jobs','mailman','Cartero','Mailman','MEIL-man',15),
  ('jobs','scientist','Cientifico','Scientist','SAIN-tist',16),
  ('jobs','waiter','Mesero','Waiter','UEI-ter',17),
  ('jobs','ballerina','Bailarina','Ballerina','ba-le-RI-na',18),
  ('jobs','clown','Payaso','Clown','klaun',19),
  ('jobs','plumber','Plomero','Plumber','PLA-mer',20),
  ('instruments','drum','Tambor','Drum','dram',1),
  ('instruments','flute','Flauta','Flute','fluut',2),
  ('instruments','guitar','Guitarra','Guitar','gui-TAR',3),
  ('instruments','maracas','Maracas','Maracas','ma-RA-kas',4),
  ('instruments','piano','Piano','Piano','PIA-nou',5),
  ('instruments','saxophone','Saxofon','Saxophone','SAK-so-foun',6),
  ('instruments','tambourine','Pandereta','Tambourine','tam-bu-RIN',7),
  ('instruments','trumpet','Trompeta','Trumpet','TRAM-pet',8),
  ('instruments','violin','Violin','Violin','vai-o-LIN',9),
  ('instruments','xylophone','Xilofono','Xylophone','SAI-lo-foun',10),
  ('instruments','accordion','Acordeon','Accordion','a-KOR-di-on',11)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;