insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('pets','dog','Perro','Dog','dog',1),
  ('pets','cat','Gato','Cat','kat',2),
  ('pets','rabbit','Conejo','Rabbit','RA-bit',3),
  ('pets','goldfish','Pez dorado','Goldfish','GOLD-fish',4),
  ('pets','hamster','Hamster','Hamster','JAMS-ter',5),
  ('pets','turtle','Tortuga','Turtle','TER-tel',6),
  ('pets','parakeet','Periquito','Parakeet','PA-ra-kit',7),
  ('pets','canary','Canario','Canary','ka-NE-ri',8),
  ('pets','chinchilla','Chinchilla','Chinchilla','chin-CHI-la',9),
  ('pets','ferret','Huron','Ferret','FE-ret',10),
  ('pets','gecko','Geco','Gecko','GE-kou',11),
  ('pets','guinea-pig','Cobayo','Guinea Pig','GUI-ni pig',12),
  ('pets','kitten','Gatito','Kitten','KI-ten',13),
  ('pets','mouse','Raton','Mouse','maus',14),
  ('pets','puppy','Perrito','Puppy','PA-pi',15),
  ('pets','cockatiel','Cacatua','Cockatiel','ko-ka-TIL',16),
  ('pets','frog','Rana','Frog','frog',17),
  ('pets','hermit-crab','Cangrejo ermitano','Hermit Crab','JER-mit krab',18),
  ('pets','snake','Serpiente','Snake','sneik',19),
  ('pets','tortoise','Tortuga terrestre','Tortoise','TOR-tes',20),
  ('farm','cow','Vaca','Cow','kau',1),
  ('farm','pig','Cerdo','Pig','pig',2),
  ('farm','horse','Caballo','Horse','jors',3),
  ('farm','hen','Gallina','Hen','jen',4),
  ('farm','duck','Pato','Duck','dak',5),
  ('farm','sheep','Oveja','Sheep','shiip',6),
  ('farm','rooster','Gallo','Rooster','RUS-ter',7),
  ('farm','bull','Toro','Bull','bul',8),
  ('farm','donkey','Burro','Donkey','DON-ki',9),
  ('farm','foal','Potro','Foal','foul',10),
  ('farm','goat','Cabra','Goat','gout',11),
  ('farm','goose','Ganso','Goose','guus',12),
  ('farm','lamb','Cordero','Lamb','lam',13),
  ('farm','llama','Llama','Llama','LLA-ma',14),
  ('farm','turkey','Pavo','Turkey','TER-ki',15),
  ('farm','alpaca','Alpaca','Alpaca','al-PA-ka',16),
  ('farm','calf','Ternero','Calf','kaf',17),
  ('farm','chick','Pollito','Chick','chik',18),
  ('farm','piglet','Cerdito','Piglet','PIG-let',19),
  ('farm','pony','Poni','Pony','POU-ni',20),
  ('wild','lion','Leon','Lion','LAI-on',1),
  ('wild','tiger','Tigre','Tiger','TAI-ger',2),
  ('wild','elephant','Elefante','Elephant','E-le-fant',3),
  ('wild','zebra','Cebra','Zebra','ZI-bra',4),
  ('wild','giraffe','Jirafa','Giraffe','lli-RAF',5),
  ('wild','hippo','Hipopotamo','Hippo','JI-po',6),
  ('wild','rhinoceros','Rinoceronte','Rhinoceros','rai-NO-se-ros',7),
  ('wild','camel','Camello','Camel','KA-mel',8),
  ('wild','cheetah','Guepardo','Cheetah','CHII-ta',9),
  ('wild','crocodile','Cocodrilo','Crocodile','KRO-ko-dail',10),
  ('wild','gorilla','Gorila','Gorilla','go-RI-la',11),
  ('wild','kangaroo','Canguro','Kangaroo','kan-ga-RU',12),
  ('wild','koala','Koala','Koala','ko-A-la',13),
  ('wild','leopard','Leopardo','Leopard','LE-pard',14),
  ('wild','monkey','Mono','Monkey','MAN-ki',15),
  ('wild','panda','Panda','Panda','PAN-da',16),
  ('wild','sloth','Perezoso','Sloth','sloz',17),
  ('wild','antelope','Antilope','Antelope','AN-te-loup',18),
  ('wild','buffalo','Bufalo','Buffalo','BA-fa-lou',19),
  ('wild','lemur','Lemur','Lemur','LII-mer',20),
  ('forest','fox','Zorro','Fox','foks',1),
  ('forest','deer','Ciervo','Deer','diir',2),
  ('forest','wolf','Lobo','Wolf','wulf',3),
  ('forest','owl','Buho','Owl','aul',4),
  ('forest','squirrel','Ardilla','Squirrel','SKUE-rel',5),
  ('forest','raccoon','Mapache','Raccoon','ra-KUN',6),
  ('forest','bear','Oso','Bear','ber',7),
  ('forest','badger','Tejon','Badger','BA-ller',8),
  ('forest','beaver','Castor','Beaver','BII-ver',9),
  ('forest','boar','Jabali','Boar','bor',10),
  ('forest','chipmunk','Ardilla listada','Chipmunk','CHIP-mank',11),
  ('forest','hedgehog','Erizo','Hedgehog','JELL-jog',12),
  ('forest','mole','Topo','Mole','moul',13),
  ('forest','moose','Alce','Moose','mus',14),
  ('forest','skunk','Zorrillo','Skunk','skank',15),
  ('forest','lynx','Lince','Lynx','links',16),
  ('forest','otter','Nutria','Otter','O-ter',17),
  ('forest','porcupine','Puercoespin','Porcupine','POR-kiu-pain',18),
  ('forest','salamander','Salamandra','Salamander','SA-la-man-der',19),
  ('forest','weasel','Comadreja','Weasel','UII-sel',20),
  ('ocean','dolphin','Delfin','Dolphin','DOL-fin',1),
  ('ocean','shark','Tiburon','Shark','shark',2),
  ('ocean','octopus','Pulpo','Octopus','OK-to-pus',3),
  ('ocean','whale','Ballena','Whale','weil',4),
  ('ocean','starfish','Estrella de mar','Starfish','STAR-fish',5),
  ('ocean','seahorse','Caballito de mar','Seahorse','SI-jors',6),
  ('ocean','jellyfish','Medusa','Jellyfish','LLE-li-fish',7),
  ('ocean','clownfish','Pez payaso','Clownfish','KLAUN-fish',8),
  ('ocean','crab','Cangrejo','Crab','krab',9),
  ('ocean','lobster','Langosta','Lobster','LOBS-ter',10),
  ('ocean','narwhal','Narval','Narwhal','NAR-ual',11),
  ('ocean','orca','Orca','Orca','OR-ka',12),
  ('ocean','penguin','Pinguino','Penguin','PEN-guin',13),
  ('ocean','seal','Foca','Seal','siil',14),
  ('ocean','shrimp','Camaron','Shrimp','shrimp',15),
  ('ocean','stingray','Raya','Stingray','STIN-grei',16),
  ('ocean','walrus','Morsa','Walrus','UOL-rus',17),
  ('ocean','eel','Anguila','Eel','iil',18),
  ('ocean','sea-turtle','Tortuga marina','Sea Turtle','sii TER-tel',19),
  ('ocean','swordfish','Pez espada','Swordfish','SORD-fish',20),
  ('flying','eagle','Aguila','Eagle','I-gol',1),
  ('flying','falcon','Halcon','Falcon','FAL-kon',2),
  ('flying','parrot','Loro','Parrot','PE-rot',3),
  ('flying','hummingbird','Colibri','Hummingbird','JA-ming-berd',4),
  ('flying','bat','Murcielago','Bat','bat',5),
  ('flying','swan','Cisne','Swan','suan',6),
  ('flying','seagull','Gaviota','Seagull','SI-gal',7),
  ('flying','dove','Paloma','Dove','dav',8),
  ('flying','flamingo','Flamenco','Flamingo','fla-MIN-gou',9),
  ('flying','peacock','Pavo real','Peacock','PII-kok',10),
  ('flying','pelican','Pelicano','Pelican','PE-li-kan',11),
  ('flying','robin','Petirrojo','Robin','RO-bin',12),
  ('flying','stork','Ciguena','Stork','stork',13),
  ('flying','toucan','Tucan','Toucan','TU-kan',14),
  ('flying','woodpecker','Pajaro carpintero','Woodpecker','UUD-pe-ker',15),
  ('flying','cardinal','Cardenal','Cardinal','KAR-di-nal',16),
  ('flying','crow','Cuervo','Crow','krou',17),
  ('flying','ostrich','Avestruz','Ostrich','OS-trich',18),
  ('flying','pigeon','Paloma','Pigeon','PI-llon',19),
  ('flying','sparrow','Gorrion','Sparrow','SPE-rou',20),
  ('bugs','bee','Abeja','Bee','bii',1),
  ('bugs','butterfly','Mariposa','Butterfly','BA-ter-flai',2),
  ('bugs','ant','Hormiga','Ant','ant',3),
  ('bugs','ladybug','Mariquita','Ladybug','LEI-di-bag',4),
  ('bugs','beetle','Escarabajo','Beetle','BI-tel',5),
  ('bugs','spider','Arana','Spider','SPAI-der',6),
  ('bugs','snail','Caracol','Snail','sneil',7),
  ('bugs','centipede','Cienpies','Centipede','SEN-ti-piid',8),
  ('bugs','cricket','Grillo','Cricket','KRI-ket',9),
  ('bugs','dragonfly','Libelula','Dragonfly','DRA-gon-flai',10),
  ('bugs','firefly','Luciernaga','Firefly','FAIR-flai',11),
  ('bugs','grasshopper','Saltamontes','Grasshopper','GRAS-jo-per',12),
  ('bugs','moth','Polilla','Moth','moz',13),
  ('bugs','wasp','Avispa','Wasp','uasp',14),
  ('bugs','worm','Gusano','Worm','uerm',15),
  ('bugs','caterpillar','Oruga','Caterpillar','KA-ter-pi-ler',16),
  ('bugs','fly','Mosca','Fly','flai',17),
  ('bugs','mosquito','Mosquito','Mosquito','mos-KI-tou',18),
  ('bugs','scorpion','Escorpion','Scorpion','SKOR-pion',19),
  ('bugs','slug','Babosa','Slug','slag',20),
  ('dinosaurs','ankylosaurus','Anquilosaurio','Ankylosaurus','an-kai-lo-SOR-us',1),
  ('dinosaurs','baby-dino','Bebe dino','Baby Dino','BEI-bi DAI-no',2),
  ('dinosaurs','brontosaurus','Brontosaurio','Brontosaurus','bron-to-SOR-us',3),
  ('dinosaurs','dino-egg','Huevo de dino','Dino Egg','DAI-no eg',4),
  ('dinosaurs','pterodactyl','Pterodactilo','Pterodactyl','te-ro-DAK-til',5),
  ('dinosaurs','raptor','Raptor','Raptor','RAP-tor',6),
  ('dinosaurs','spinosaurus','Espinosaurio','Spinosaurus','spi-no-SOR-us',7),
  ('dinosaurs','stegosaurus','Estegosaurio','Stegosaurus','ste-go-SOR-us',8),
  ('dinosaurs','t-rex','Tiranosaurio','T-Rex','TI-reks',9),
  ('dinosaurs','triceratops','Triceratops','Triceratops','trai-SE-ra-tops',10),
  ('dinosaurs','allosaurus','Alosaurio','Allosaurus','a-lo-SOR-us',11),
  ('dinosaurs','dilophosaurus','Dilofosaurio','Dilophosaurus','di-lo-fo-SOR-us',12),
  ('dinosaurs','dino-skull','Craneo de dino','Dino Skull','DAI-no skal',13),
  ('dinosaurs','fossil','Fosil','Fossil','FO-sil',14),
  ('dinosaurs','pachycephalosaurus','Paquicefalosaurio','Pachycephalosaurus','pa-ki-se-fa-lo-SOR-us',15),
  ('dinosaurs','parasaurolophus','Parasaurolofo','Parasaurolophus','pa-ra-so-RO-lo-fus',16),
  ('dinosaurs','diplodocus','Diplodocus','Diplodocus','di-PLO-do-kus',17),
  ('dinosaurs','iguanodon','Iguanodonte','Iguanodon','i-GUA-no-don',18),
  ('dinosaurs','plesiosaurus','Plesiosaurio','Plesiosaurus','ple-sio-SOR-us',19),
  ('dinosaurs','volcano','Volcan','Volcano','vol-KEI-nou',20),
  ('vehicles','airplane','Avion','Airplane','ER-plein',1),
  ('vehicles','bus','Autobus','Bus','bas',2),
  ('vehicles','car','Carro','Car','kar',3),
  ('vehicles','fire-truck','Camion de bomberos','Fire Truck','fair trak',4),
  ('vehicles','helicopter','Helicoptero','Helicopter','JE-li-kop-ter',5),
  ('vehicles','police-car','Patrulla','Police Car','po-LIS kar',6),
  ('vehicles','sailboat','Velero','Sailboat','SEIL-bout',7),
  ('vehicles','tractor','Tractor','Tractor','TRAK-tor',8),
  ('vehicles','train','Tren','Train','trein',9),
  ('vehicles','truck','Camion','Truck','trak',10)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;