insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('home','door','Puerta','Door','dor',5),
  ('home','fireplace','Chimenea','Fireplace','FAIR-pleis',6),
  ('home','lamp','Lampara','Lamp','lamp',7),
  ('home','mirror','Espejo','Mirror','MI-ror',8),
  ('home','pillow','Almohada','Pillow','PI-lou',9),
  ('home','rug','Tapete','Rug','rag',10),
  ('home','shelf','Estante','Shelf','shelf',11),
  ('home','sink','Lavabo','Sink','sink',12),
  ('home','sofa','Sofa','Sofa','SOU-fa',13),
  ('home','stairs','Escaleras','Stairs','sters',14),
  ('home','table','Mesa','Table','TEI-bel',15),
  ('home','window','Ventana','Window','UIN-dou',16),
  ('home','blanket','Cobija','Blanket','BLAN-ket',17),
  ('home','television','Television','Television','TE-le-vi-shon',18),
  ('home','toilet','Inodoro','Toilet','TOI-let',19),
  ('home','wardrobe','Armario','Wardrobe','UOR-droub',20),
  ('kitchen','bottle','Botella','Bottle','BO-tel',1),
  ('kitchen','bowl','Tazon','Bowl','boul',2),
  ('kitchen','cup','Taza','Cup','kap',3),
  ('kitchen','fork','Tenedor','Fork','fork',4),
  ('kitchen','knife','Cuchillo','Knife','naif',5),
  ('kitchen','napkin','Servilleta','Napkin','NAP-kin',6),
  ('kitchen','pan','Sarten','Pan','pan',7),
  ('kitchen','pot','Olla','Pot','pot',8),
  ('kitchen','refrigerator','Refrigerador','Refrigerator','ri-FRI-lle-rei-tor',9),
  ('kitchen','spoon','Cuchara','Spoon','spun',10),
  ('kitchen','stove','Estufa','Stove','stouv',11),
  ('kitchen','teapot','Tetera','Teapot','TII-pot',12),
  ('kitchen','blender','Licuadora','Blender','BLEN-der',13),
  ('kitchen','glass','Vaso','Glass','glas',14),
  ('kitchen','jar','Frasco','Jar','llar',15),
  ('kitchen','kettle','Hervidor','Kettle','KE-tel',16),
  ('kitchen','mug','Tarro','Mug','mag',17),
  ('kitchen','oven','Horno','Oven','A-ven',18),
  ('kitchen','plate','Plato','Plate','pleit',19),
  ('kitchen','toaster','Tostadora','Toaster','TOUS-ter',20),
  ('toys','board-game','Juego de mesa','Board Game','bord geim',1),
  ('toys','building-blocks','Bloques','Building Blocks','BIL-ding bloks',2),
  ('toys','doll','Muneca','Doll','dol',3),
  ('toys','dollhouse','Casa de munecas','Dollhouse','DOL-jaus',4),
  ('toys','marbles','Canicas','Marbles','MAR-bels',5),
  ('toys','rocking-horse','Caballito','Rocking Horse','RO-king jors',6),
  ('toys','spinning-top','Trompo','Spinning Top','SPI-ning top',7),
  ('toys','teddy-bear','Osito de peluche','Teddy Bear','TE-di ber',8),
  ('toys','ball','Pelota','Ball','bol',9),
  ('toys','bubbles','Burbujas','Bubbles','BA-bels',10),
  ('toys','jack-in-the-box','Caja sorpresa','Jack-in-the-box','llak-in-de-BOKS',11),
  ('toys','kaleidoscope','Caleidoscopio','Kaleidoscope','ka-LAI-dos-koup',12),
  ('toys','play-dough','Plastilina','Play Dough','plei dou',13),
  ('toys','puzzle','Rompecabezas','Puzzle','PA-sel',14),
  ('toys','rattle','Sonaja','Rattle','RA-tel',15),
  ('toys','slinky','Resorte','Slinky','SLIN-ki',16),
  ('toys','toy-robot','Robot de juguete','Toy Robot','toi ROU-bot',17),
  ('toys','toy-soldier','Soldadito','Toy Soldier','toi SOUL-ller',18),
  ('toys','wagon','Carrito','Wagon','UA-gon',19),
  ('toys','yo-yo','Yoyo','Yo-Yo','IOU-iou',20),
  ('school','backpack','Mochila','Backpack','BAK-pak',1),
  ('school','desk','Pupitre','Desk','desk',2),
  ('school','globe','Globo terraqueo','Globe','gloub',3),
  ('school','glue','Pegamento','Glue','glu',4),
  ('school','marker','Marcador','Marker','MAR-ker',5),
  ('school','notebook','Cuaderno','Notebook','NOUT-buk',6),
  ('school','paint','Pintura','Paint','peint',7),
  ('school','paper','Papel','Paper','PEI-per',8),
  ('school','ruler','Regla','Ruler','RU-ler',9),
  ('school','scissors','Tijeras','Scissors','SI-sors',10),
  ('school','book','Libro','Book','buk',11),
  ('school','calculator','Calculadora','Calculator','KAL-kiu-lei-tor',12),
  ('school','chalk','Gis','Chalk','chok',13),
  ('school','chalkboard','Pizarron','Chalkboard','CHOK-bord',14),
  ('school','crayon','Crayon','Crayon','KREI-on',15),
  ('school','eraser','Goma de borrar','Eraser','i-REI-ser',16),
  ('school','paintbrush','Pincel','Paintbrush','PEINT-brash',17),
  ('school','pencil','Lapiz','Pencil','PEN-sil',18),
  ('school','pencil-case','Estuche','Pencil Case','PEN-sil keis',19),
  ('school','stapler','Engrapadora','Stapler','STEI-pler',20),
  ('nature','bush','Arbusto','Bush','bush',1),
  ('nature','cave','Cueva','Cave','keiv',2),
  ('nature','flower','Flor','Flower','FLAU-er',3),
  ('nature','grass','Pasto','Grass','gras',4),
  ('nature','hill','Colina','Hill','jil',5),
  ('nature','lake','Lago','Lake','leik',6),
  ('nature','pinecone','Pina de pino','Pinecone','PAIN-koun',7),
  ('nature','pond','Estanque','Pond','pond',8),
  ('nature','river','Rio','River','RI-ver',9),
  ('nature','tree','Arbol','Tree','trii',10),
  ('nature','waterfall','Cascada','Waterfall','UO-ter-fol',11),
  ('nature','acorn','Bellota','Acorn','EI-korn',12),
  ('nature','cactus','Cactus','Cactus','KAK-tus',13),
  ('nature','island','Isla','Island','AI-land',14),
  ('nature','leaf','Hoja','Leaf','liif',15),
  ('nature','log','Tronco','Log','log',16),
  ('nature','mountain','Montana','Mountain','MAUN-tin',17),
  ('nature','rock','Roca','Rock','rok',18),
  ('nature','seed','Semilla','Seed','siid',19),
  ('nature','sprout','Brote','Sprout','spraut',20),
  ('weather','puddle','Charco','Puddle','PA-del',1),
  ('weather','tornado','Tornado','Tornado','tor-NEI-dou',2),
  ('weather','umbrella','Paraguas','Umbrella','am-BRE-la',3),
  ('weather','wind','Viento','Wind','uind',4),
  ('weather','cloud','Nube','Cloud','klaud',5),
  ('weather','fog','Niebla','Fog','fog',6),
  ('weather','hail','Granizo','Hail','jeil',7),
  ('weather','icicle','Carambano','Icicle','AI-si-kel',8),
  ('weather','lightning','Rayo','Lightning','LAIT-ning',9),
  ('weather','rain','Lluvia','Rain','rein',10),
  ('weather','rainbow','Arcoiris','Rainbow','REIN-bou',11),
  ('weather','snow','Nieve','Snow','snou',12),
  ('weather','snowflake','Copo de nieve','Snowflake','SNOU-fleik',13),
  ('weather','storm','Tormenta','Storm','storm',14),
  ('city','bus-stop','Parada de autobus','Bus Stop','bas stop',1),
  ('city','gas-station','Gasolinera','Gas Station','gas STEI-shon',2),
  ('city','house','Casa','House','jaus',3),
  ('city','library','Biblioteca','Library','LAI-bre-ri',4),
  ('city','park','Parque','Park','park',5),
  ('city','playground','Parque de juegos','Playground','PLEI-graund',6),
  ('city','police-station','Estacion de policia','Police Station','po-LIS STEI-shon',7),
  ('city','post-office','Oficina de correos','Post Office','poust O-fis',8),
  ('city','store','Tienda','Store','stor',9),
  ('city','bakery','Panaderia','Bakery','BEI-ke-ri',10),
  ('city','bridge','Puente','Bridge','brill',11),
  ('city','fire-station','Estacion de bomberos','Fire Station','fair STEI-shon',12),
  ('city','hospital','Hospital','Hospital','JOS-pi-tal',13),
  ('city','restaurant','Restaurante','Restaurant','RES-to-rant',14),
  ('city','school-building','Escuela','School Building','skul BIL-ding',15),
  ('city','skyscraper','Rascacielos','Skyscraper','SKAI-skrei-per',16),
  ('city','traffic-light','Semaforo','Traffic Light','TRA-fik lait',17),
  ('city','zoo','Zoologico','Zoo','zuu',18),
  ('tools','drill','Taladro','Drill','dril',1),
  ('tools','level','Nivel','Level','LE-vel',2),
  ('tools','pliers','Pinzas','Pliers','PLAI-ers',3),
  ('tools','rake','Rastrillo','Rake','reik',4),
  ('tools','saw','Serrucho','Saw','so',5),
  ('tools','screw','Tornillo','Screw','skru',6),
  ('tools','tape-measure','Cinta metrica','Tape Measure','teip ME-sher',7),
  ('tools','bolt','Perno','Bolt','boult',8),
  ('tools','hammer','Martillo','Hammer','JA-mer',9),
  ('tools','ladder','Escalera','Ladder','LA-der',10),
  ('tools','nail','Clavo','Nail','neil',11),
  ('tools','paint-roller','Rodillo','Paint Roller','peint ROU-ler',12),
  ('tools','screwdriver','Desarmador','Screwdriver','SKRU-drai-ver',13),
  ('tools','shovel','Pala','Shovel','SHA-vel',14),
  ('tools','toolbox','Caja de herramientas','Toolbox','TUL-boks',15),
  ('tools','wrench','Llave','Wrench','rench',16)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;

select 'drawings' t, count(*) from public.drawings;