insert into public.drawings (world_id, slug, name_es, name_en, phonetic_es, line_art_path, sort_order, is_active)
select w.id, d.slug, d.name_es, d.name_en, d.phonetic_es,
       'line-art/' || d.world_slug || '/' || d.slug || '.png', d.sort_order, true
from (values
  ('instruments','banjo','Banjo','Banjo','BAN-llo',12),
  ('instruments','bongos','Bongos','Bongos','BON-gous',13),
  ('instruments','cello','Violonchelo','Cello','CHE-lou',14),
  ('instruments','cymbals','Platillos','Cymbals','SIM-bals',15),
  ('instruments','harmonica','Armonica','Harmonica','jar-MO-ni-ka',16),
  ('instruments','harp','Arpa','Harp','jarp',17),
  ('instruments','ukulele','Ukelele','Ukulele','iu-ku-LEI-li',18),
  ('instruments','recorder','Flauta dulce','Recorder','ri-KOR-der',19),
  ('instruments','trombone','Trombon','Trombone','trom-BOUN',20),
  ('beach','beach-ball','Pelota de playa','Beach Ball','biich bol',1),
  ('beach','beach-umbrella','Sombrilla','Beach Umbrella','biich am-BRE-la',2),
  ('beach','coconut-drink','Coco','Coconut Drink','KO-ko-nat drink',3),
  ('beach','flip-flops','Sandalias','Flip Flops','flip flops',4),
  ('beach','palm-tree','Palmera','Palm Tree','paam trii',5),
  ('beach','popsicle','Paleta','Popsicle','POP-si-kel',6),
  ('beach','sand-bucket','Cubeta','Sand Bucket','sand BA-ket',7),
  ('beach','sandcastle','Castillo de arena','Sandcastle','SAND-ka-sel',8),
  ('beach','seashell','Concha','Seashell','SII-shel',9),
  ('beach','surfboard','Tabla de surf','Surfboard','SERF-bord',10),
  ('beach','anchor','Ancla','Anchor','AN-ker',11),
  ('beach','beach-towel','Toalla de playa','Beach Towel','biich TAU-el',12),
  ('beach','life-jacket','Chaleco salvavidas','Life Jacket','laif LLA-ket',13),
  ('beach','lighthouse','Faro','Lighthouse','LAIT-jaus',14),
  ('beach','sand-dollar','Dolar de arena','Sand Dollar','sand DO-lar',15),
  ('beach','sunglasses','Lentes de sol','Sunglasses','SAN-gla-ses',16),
  ('beach','sunscreen','Bloqueador','Sunscreen','SAN-skriin',17),
  ('beach','swimsuit','Traje de bano','Swimsuit','SUIM-sut',18),
  ('beach','beach-chair','Silla de playa','Beach Chair','biich cher',19),
  ('beach','snorkel','Esnorquel','Snorkel','SNOR-kel',20),
  ('holidays','balloon','Globo','Balloon','ba-LUN',1),
  ('holidays','christmas-tree','Arbol de Navidad','Christmas Tree','KRIS-mas trii',2),
  ('holidays','easter-egg','Huevo de Pascua','Easter Egg','IS-ter eg',3),
  ('holidays','ghost','Fantasma','Ghost','goust',4),
  ('holidays','gift','Regalo','Gift','gift',5),
  ('holidays','heart','Corazon','Heart','jart',6),
  ('holidays','party-hat','Gorro de fiesta','Party Hat','PAR-ti jat',7),
  ('holidays','pumpkin','Calabaza','Pumpkin','PAMP-kin',8),
  ('holidays','santa','Santa','Santa','SAN-ta',9),
  ('holidays','snowman','Muneco de nieve','Snowman','SNOU-man',10),
  ('holidays','candy-cane','Baston de dulce','Candy Cane','KAN-di kein',11),
  ('holidays','confetti','Confeti','Confetti','kon-FE-ti',12),
  ('holidays','fireworks','Fuegos artificiales','Fireworks','FAIR-uerks',13),
  ('holidays','lantern','Farolito','Lantern','LAN-tern',14),
  ('holidays','ornament','Esfera navidena','Ornament','OR-na-ment',15),
  ('holidays','pinata','Pinata','Pinata','pin-IA-ta',16),
  ('holidays','reindeer','Reno','Reindeer','REIN-diir',17),
  ('holidays','stocking','Calceta navidena','Stocking','STO-king',18),
  ('holidays','gingerbread-man','Galleta de jengibre','Gingerbread Man','LLIN-ller-bred man',19),
  ('holidays','wreath','Corona navidena','Wreath','riiz',20),
  ('family','baby','Bebe','Baby','BEI-bi',1),
  ('family','boy','Nino','Boy','boi',2),
  ('family','brother','Hermano','Brother','BRA-der',3),
  ('family','cousin','Primo','Cousin','KA-sin',4),
  ('family','dad','Papa','Dad','dad',5),
  ('family','family','Familia','Family','FA-mi-li',6),
  ('family','friend','Amigo','Friend','frend',7),
  ('family','girl','Nina','Girl','guerl',8),
  ('family','grandma','Abuela','Grandma','GRAND-ma',9),
  ('family','grandpa','Abuelo','Grandpa','GRAND-pa',10),
  ('family','sister','Hermana','Sister','SIS-ter',11),
  ('family','toddler','Nene','Toddler','TOD-ler',12),
  ('family','twins','Gemelos','Twins','tuins',13),
  ('family','aunt','Tia','Aunt','ant',14),
  ('family','mom','Mama','Mom','mom',15),
  ('family','uncle','Tio','Uncle','AN-kel',16),
  ('body','finger','Dedo','Finger','FIN-ger',1),
  ('body','hair','Cabello','Hair','jer',2),
  ('body','hand','Mano','Hand','jand',3),
  ('body','head','Cabeza','Head','jed',4),
  ('body','neck','Cuello','Neck','nek',5),
  ('body','nose','Nariz','Nose','nous',6),
  ('body','arm','Brazo','Arm','arm',7),
  ('body','back','Espalda','Back','bak',8),
  ('body','cheek','Mejilla','Cheek','chiik',9),
  ('body','ear','Oreja','Ear','iir',10),
  ('body','eye','Ojo','Eye','ai',11),
  ('body','foot','Pie','Foot','fut',12),
  ('body','knee','Rodilla','Knee','nii',13),
  ('body','leg','Pierna','Leg','leg',14),
  ('body','mouth','Boca','Mouth','mauz',15),
  ('body','shoulder','Hombro','Shoulder','SHOUL-der',16),
  ('body','teeth','Dientes','Teeth','tiiz',17),
  ('body','toe','Dedo del pie','Toe','tou',18),
  ('body','tongue','Lengua','Tongue','tang',19),
  ('body','tummy','Pancita','Tummy','TA-mi',20),
  ('clothes','coat','Abrigo','Coat','kout',1),
  ('clothes','dress','Vestido','Dress','dres',2),
  ('clothes','gloves','Guantes','Gloves','glavs',3),
  ('clothes','hat','Sombrero','Hat','jat',4),
  ('clothes','jacket','Chaqueta','Jacket','LLA-ket',5),
  ('clothes','mittens','Mitones','Mittens','MI-tens',6),
  ('clothes','shirt','Camisa','Shirt','shert',7),
  ('clothes','shoes','Zapatos','Shoes','shus',8),
  ('clothes','skirt','Falda','Skirt','skert',9),
  ('clothes','sweater','Sueter','Sweater','SUE-ter',10),
  ('clothes','t-shirt','Playera','T-Shirt','TI-shert',11),
  ('clothes','belt','Cinturon','Belt','belt',12),
  ('clothes','boots','Botas','Boots','buuts',13),
  ('clothes','cap','Gorra','Cap','kap',14),
  ('clothes','pajamas','Pijama','Pajamas','pa-LLA-mas',15),
  ('clothes','pants','Pantalon','Pants','pants',16),
  ('clothes','sandals','Sandalias','Sandals','SAN-dals',17),
  ('clothes','scarf','Bufanda','Scarf','skarf',18),
  ('clothes','shorts','Shorts','Shorts','shorts',19),
  ('clothes','socks','Calcetines','Socks','soks',20),
  ('colors','blue','Azul','Blue','blu',1),
  ('colors','gold','Dorado','Gold','gould',2),
  ('colors','pink','Rosa','Pink','pink',3),
  ('colors','purple','Morado','Purple','PER-pel',4),
  ('colors','red','Rojo','Red','red',5),
  ('colors','beige','Beige','Beige','beish',6),
  ('colors','black','Negro','Black','blak',7),
  ('colors','brown','Cafe','Brown','braun',8),
  ('colors','gray','Gris','Gray','grei',9),
  ('colors','green','Verde','Green','griin',10),
  ('colors','orange','Naranja','Orange','O-rinll',11),
  ('colors','silver','Plateado','Silver','SIL-ver',12),
  ('colors','turquoise','Turquesa','Turquoise','TER-koiz',13),
  ('colors','violet','Violeta','Violet','VAI-o-let',14),
  ('colors','white','Blanco','White','uait',15),
  ('colors','yellow','Amarillo','Yellow','IE-lou',16),
  ('shapes','arrow','Flecha','Arrow','E-rou',1),
  ('shapes','circle','Circulo','Circle','SER-kel',2),
  ('shapes','cone','Cono','Cone','koun',3),
  ('shapes','cylinder','Cilindro','Cylinder','SI-lin-der',4),
  ('shapes','oval','Ovalo','Oval','OU-val',5),
  ('shapes','rectangle','Rectangulo','Rectangle','rek-TAN-gol',6),
  ('shapes','triangle','Triangulo','Triangle','TRAI-an-gol',7),
  ('shapes','cube','Cubo','Cube','kiub',8),
  ('shapes','diamond','Rombo','Diamond','DAI-mond',9),
  ('shapes','hexagon','Hexagono','Hexagon','JEK-sa-gon',10),
  ('shapes','octagon','Octagono','Octagon','OK-ta-gon',11),
  ('shapes','pentagon','Pentagono','Pentagon','PEN-ta-gon',12),
  ('shapes','pyramid','Piramide','Pyramid','PI-ra-mid',13),
  ('shapes','sphere','Esfera','Sphere','sfiir',14),
  ('shapes','square','Cuadrado','Square','skuer',15),
  ('numbers','one','Uno','One','uan',1),
  ('numbers','two','Dos','Two','tu',2),
  ('numbers','three','Tres','Three','zrii',3),
  ('numbers','four','Cuatro','Four','for',4),
  ('numbers','five','Cinco','Five','faiv',5),
  ('numbers','six','Seis','Six','siks',6),
  ('numbers','seven','Siete','Seven','SE-ven',7),
  ('numbers','eight','Ocho','Eight','eit',8),
  ('numbers','nine','Nueve','Nine','nain',9),
  ('numbers','ten','Diez','Ten','ten',10),
  ('numbers','eleven','Once','Eleven','i-LE-ven',11),
  ('numbers','twelve','Doce','Twelve','tuelv',12),
  ('numbers','thirteen','Trece','Thirteen','zer-TIN',13),
  ('numbers','fourteen','Catorce','Fourteen','for-TIN',14),
  ('numbers','fifteen','Quince','Fifteen','fif-TIN',15),
  ('numbers','sixteen','Dieciseis','Sixteen','siks-TIN',16),
  ('numbers','seventeen','Diecisiete','Seventeen','se-ven-TIN',17),
  ('numbers','eighteen','Dieciocho','Eighteen','ei-TIN',18),
  ('numbers','nineteen','Diecinueve','Nineteen','nain-TIN',19),
  ('numbers','twenty','Veinte','Twenty','TUEN-ti',20),
  ('home','bathtub','Tina','Bathtub','BAZ-tab',1),
  ('home','bed','Cama','Bed','bed',2),
  ('home','chair','Silla','Chair','cher',3),
  ('home','clock','Reloj','Clock','klok',4)
) as d(world_slug, slug, name_es, name_en, phonetic_es, sort_order)
join public.worlds w on w.slug = d.world_slug
on conflict (world_id, slug) do update set
  name_es = excluded.name_es, name_en = excluded.name_en,
  phonetic_es = excluded.phonetic_es, line_art_path = excluded.line_art_path,
  sort_order = excluded.sort_order, is_active = true;